#!/bin/bash
#BSUB -q long
#BSUB -n 8
#BSUB -W 01:00
#BSUB -R "span[hosts=1] rusage[mem=3]"
#BSUB -o logs/fqcp_%J.out
#BSUB -e logs/fqcp_%J.err
set -euo pipefail

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/africanveg/gwnjeri/conda_envs/aiv_env_new || export PATH="/share/africanveg/gwnjeri/conda_envs/aiv_env_new/bin:$PATH"
mkdir -p fastqc_pre
fastqc -t 8 -o fastqc_pre fastq_merged/*.fastq.gz
multiqc -o fastqc_pre fastqc_pre
