#!/bin/bash
# Resources per Hazel docs:
#BSUB -n 8
#BSUB -W 02:00
#BSUB -R "span[hosts=1]"
#BSUB -o logs/fastp_%J_%I.out
#BSUB -e logs/fastp_%J_%I.err
set -euo pipefail

# env
source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/africanveg/gwnjeri/conda_envs/aiv_env_new || export PATH="/share/africanveg/gwnjeri/conda_envs/aiv_env_new/bin:$PATH"

SHEET="fastq_merged/samples.tsv"
OUT="trim"
mkdir -p "$OUT" "$OUT/reports"

# pick the Nth line for this array task
line=$(sed -n "${LSB_JOBINDEX}p" "$SHEET")
sample=$(echo "$line" | awk '{print $1}')
r1=$(echo "$line" | awk '{print $2}')
r2=$(echo "$line" | awk '{print $3}')

fastp -i "$r1" -I "$r2" \
  -o $OUT/${sample}_R1.fastq.gz -O $OUT/${sample}_R2.fastq.gz \
  -w 8 --detect_adapter_for_pe \
  --qualified_quality_phred 15 --length_required 50 \
  --json $OUT/reports/${sample}.json --html $OUT/reports/${sample}.html
